//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alinamagazinteh.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Zakaz
    {
        public int Id_zakaz { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ZakazId { get; set; }
        public Nullable<int> Kolvo_zakaz { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Zakaz_zakaz Zakaz_zakaz { get; set; }
    }
}
