//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alinamagazinteh.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz_zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz_zakaz()
        {
            this.Product_Zakaz = new HashSet<Product_Zakaz>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ZakazDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Zakaz> Product_Zakaz { get; set; }
    }
}
